Add controllers
NoizyDuck/java-shareit pull request #1
Opened 2023-01-19 23:56 UTC by NoizyDuck

2023-01-20 19:19 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public Boolean getAvailable() {
Для чего этот геттер, ведь есть аннотация Data

2023-01-20 19:20 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemDto.getDescription() != null) {
Эти поля ведь и так помечены @NotNull. Проверка лишняя.

2023-01-20 19:23 UTC, EvgenyKoptubenko requested changes
Проект сделан отлично. Замечаний считай нет. Всего два, но они совсем уж незначительные

2023-01-20 20:42 UTC, NoizyDuck commented
метод убрал. Он там был потому что mapstruct вел себя не стабильно. не знаю как так

2023-01-20 20:46 UTC, NoizyDuck commented
Проверки нужны конкретно по метод update, в контроллере update  нет аннотации @Valid, с ней идёт конфликт с тестами. А для создания как раз @Valid отрабатывает выкидывая нужный код ошибки.

2023-01-21 07:49 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2023-01-27 17:28 UTC, merged