Add bookings
NoizyDuck/java-shareit pull request #2
Opened 2023-02-07 23:48 UTC by NoizyDuck

2023-02-08 19:00 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto addUser(@RequestBody @Valid UserCreateDto userDto) {
Если добавить второго такого же пользователя, то клиенту приходит 500-я ошибка. Должен быть хотя бы BadRequest, лучше Conflict

insert into users (id, email, user_name) values (default, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause

org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.UK_K8D0F2N7N88W1A16YHUA64ONX_INDEX_4 ON PUBLIC.USERS(USER_NAME NULLS FIRST) VALUES ( /* 1 */ 'nameItem' )"; SQL statement:
insert into users (id, email, user_name) values (default, ?, ?) [23505-214]

2023-02-08 19:01 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@RequestBody @Valid UserDto userDto, @PathVariable Long userId) {
Почему-то пропатчить пользователя можно только один раз. Второй раз приходит сообщение об ошибке 409
{
	"error": "wrong_emai@lmail.com"
}
А если пользователь хочет обновить только логин?

2023-02-08 19:03 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>   * TODO Sprint add-bookings.
Этот TODO похоже устарел. Лучше лишнее все из кода удалять

2023-02-08 19:16 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.findAllByOwner_IdOrderById(userId).stream().map(itemMapper::itemToDto)
Вот этот метод некрасивый. Я имею ввиду следующее:
По названию функция должна вернуть все item'ы. Но на самом деле она еще обновляет базу данных.
Получается идет один запрос на все item'ы, далее у каждого вызывается репозиторий 3 раза. Конечно классно, что писать селекты/апдейты самому не нужно, но чтобы вытащить 100 items, будет сделано 301 обращение к базе данных.

2023-02-08 19:21 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть несколько замечаний. Поправь, пожалуйста.

2023-02-10 15:12 UTC, NoizyDuck commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto addUser(@RequestBody @Valid UserCreateDto userDto) {
Есть такая проблема да. Но при валидации email возникает конфликт с тестом в постмане. Сказали валидацию убрать https://app.pachca.com/chats/3783965?message=30911971

2023-02-10 15:12 UTC, NoizyDuck commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>   * TODO Sprint add-bookings.
справедливо. убрал

2023-02-10 15:25 UTC, NoizyDuck commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@RequestBody @Valid UserDto userDto, @PathVariable Long userId) {
Подскажи, пожалуйста, как получить такую ошибку. По постману вроде все обновляется нормально. Логин (имя) обновляется по айдишнику пользователя, если в входящем теле нет email.

2023-02-10 17:59 UTC, NoizyDuck commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.findAllByOwner_IdOrderById(userId).stream().map(itemMapper::itemToDto)
Ну а если переименовать метод?) По сути он возвращает не все вещи, а только вещи одного владельца..

2023-02-10 18:22 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@RequestBody @Valid UserDto userDto, @PathVariable Long userId) {
Я просто два раза один и тот же запрос отправлял

2023-02-10 18:23 UTC, EvgenyKoptubenko approved these changes
Замечаний нет. Работа сделана хорошо.

2023-02-15 07:30 UTC, merged